import type { McpScope } from "./scopes";

export type RootOperationKind = "query" | "mutation";
export type RootFieldScopeMap = Readonly<Record<string, readonly McpScope[]>>;

type FieldGroup = readonly [fields: readonly string[], scopes: readonly McpScope[]];

function buildFieldMap(groups: readonly FieldGroup[]): RootFieldScopeMap {
  const result: Record<string, readonly McpScope[]> = {};
  for (const [fields, scopes] of groups) {
    for (const field of fields) {
      if (field in result)
        throw new Error(`Duplicate MCP scope mapping for root field '${field}'.`);
      result[field] = scopes;
    }
  }
  return Object.freeze(result);
}

/**
 * Exact root-field map generated from and reviewed against the bundled
 * `schema.graphql`. Exact names are intentional: a new Saleor root field does not
 * inherit authority merely because its name happens to share a prefix.
 */
export const ROOT_FIELD_SCOPES: Readonly<Record<RootOperationKind, RootFieldScopeMap>> = {
  query: buildFieldMap([
    [
      [
        "digitalContent",
        "digitalContents",
        "categories",
        "category",
        "collection",
        "collections",
        "product",
        "products",
        "productVariant",
        "productVariants",
        "reportProductSales",
      ],
      ["saleor:catalog:read"],
    ],
    [["warehouse", "warehouses", "stock", "stocks"], ["saleor:inventory:read"]],
    [["productType", "productTypes", "attributes", "attribute"], ["saleor:attributes:read"]],
    [
      [
        "orderSettings",
        "homepageEvents",
        "order",
        "orders",
        "draftOrders",
        "ordersTotal",
        "orderByToken",
      ],
      ["saleor:orders:read"],
    ],
    [["checkout", "checkouts", "checkoutLines"], ["saleor:checkouts:read"]],
    [["payment", "payments", "transaction"], ["saleor:payments:read"]],
    [["address", "customers"], ["saleor:customers:read"]],
    [["addressValidationRules", "me"], ["saleor:identity:read"]],
    [["permissionGroups", "permissionGroup", "staffUsers"], ["saleor:staff:read"]],
    [["user"], ["saleor:customers:read", "saleor:staff:read"]],
    [
      ["sale", "sales", "voucher", "vouchers", "promotion", "promotions"],
      ["saleor:discounts:read"],
    ],
    [
      ["giftCardSettings", "giftCard", "giftCards", "giftCardCurrencies", "giftCardTags"],
      ["saleor:gift-cards:read"],
    ],
    [["page", "pages", "pageType", "pageTypes"], ["saleor:content:read"]],
    [["menu", "menus", "menuItem", "menuItems"], ["saleor:navigation:read"]],
    [["shippingZone", "shippingZones"], ["saleor:shipping:read"]],
    [
      [
        "taxConfiguration",
        "taxConfigurations",
        "taxClass",
        "taxClasses",
        "taxCountryConfiguration",
        "taxCountryConfigurations",
        "taxTypes",
      ],
      ["saleor:taxes:read"],
    ],
    [["translations", "translation"], ["saleor:translations:read"]],
    [["channel", "channels"], ["saleor:channels:read"]],
    [["appsInstallations", "apps", "app", "appExtensions", "appExtension"], ["saleor:apps:read"]],
    [["webhook", "webhookEvents", "webhookSamplePayload"], ["saleor:webhooks:read"]],
    [["shop"], ["saleor:settings:read"]],
    [["plugin", "plugins"], ["saleor:plugins:read"]],
    [["exportFile", "exportFiles"], ["saleor:exports:read"]],
    [["_entities"], ["saleor:system:read"]],
    [["_service", "__schema", "__type"], ["saleor:schema:read"]],
    [["__typename"], []],
  ]),
  mutation: buildFieldMap([
    [
      [
        "categoryCreate",
        "categoryDelete",
        "categoryBulkDelete",
        "categoryUpdate",
        "collectionAddProducts",
        "collectionCreate",
        "collectionDelete",
        "collectionReorderProducts",
        "collectionBulkDelete",
        "collectionRemoveProducts",
        "collectionUpdate",
        "collectionChannelListingUpdate",
        "productCreate",
        "productDelete",
        "productBulkCreate",
        "productBulkDelete",
        "productUpdate",
        "productChannelListingUpdate",
        "productMediaCreate",
        "productVariantReorder",
        "productMediaDelete",
        "productMediaBulkDelete",
        "productMediaReorder",
        "productMediaUpdate",
        "productReorderAttributeValues",
        "digitalContentCreate",
        "digitalContentDelete",
        "digitalContentUpdate",
        "digitalContentUrlCreate",
        "productVariantCreate",
        "productVariantDelete",
        "productVariantBulkCreate",
        "productVariantBulkUpdate",
        "productVariantBulkDelete",
        "productVariantUpdate",
        "productVariantSetDefault",
        "productVariantChannelListingUpdate",
        "productVariantReorderAttributeValues",
        "productVariantPreorderDeactivate",
        "variantMediaAssign",
        "variantMediaUnassign",
      ],
      ["saleor:catalog:write"],
    ],
    [
      [
        "createWarehouse",
        "updateWarehouse",
        "deleteWarehouse",
        "assignWarehouseShippingZone",
        "unassignWarehouseShippingZone",
        "stockBulkUpdate",
        "productVariantStocksCreate",
        "productVariantStocksDelete",
        "productVariantStocksUpdate",
      ],
      ["saleor:inventory:write"],
    ],
    [
      [
        "productAttributeAssign",
        "productAttributeAssignmentUpdate",
        "productAttributeUnassign",
        "productTypeCreate",
        "productTypeDelete",
        "productTypeBulkDelete",
        "productTypeUpdate",
        "productTypeReorderAttributes",
        "attributeCreate",
        "attributeDelete",
        "attributeUpdate",
        "attributeBulkCreate",
        "attributeBulkUpdate",
        "attributeBulkDelete",
        "attributeValueBulkDelete",
        "attributeValueCreate",
        "attributeValueDelete",
        "attributeValueUpdate",
        "attributeReorderValues",
      ],
      ["saleor:attributes:write"],
    ],
    [
      [
        "orderSettingsUpdate",
        "draftOrderComplete",
        "draftOrderCreate",
        "draftOrderDelete",
        "draftOrderBulkDelete",
        "draftOrderLinesBulkDelete",
        "draftOrderUpdate",
        "orderAddNote",
        "orderCancel",
        "orderConfirm",
        "orderFulfill",
        "orderFulfillmentCancel",
        "orderFulfillmentApprove",
        "orderFulfillmentUpdateTracking",
        "orderFulfillmentReturnProducts",
        "orderLinesCreate",
        "orderLineDelete",
        "orderLineUpdate",
        "orderDiscountAdd",
        "orderDiscountUpdate",
        "orderDiscountDelete",
        "orderLineDiscountUpdate",
        "orderLineDiscountRemove",
        "orderNoteAdd",
        "orderNoteUpdate",
        "orderUpdate",
        "orderUpdateShipping",
        "orderBulkCancel",
        "invoiceRequest",
        "invoiceRequestDelete",
        "invoiceCreate",
        "invoiceDelete",
        "invoiceUpdate",
        "invoiceSendNotification",
      ],
      ["saleor:orders:write"],
    ],
    [
      [
        "orderCapture",
        "orderFulfillmentRefundProducts",
        "orderGrantRefundCreate",
        "orderGrantRefundUpdate",
        "orderMarkAsPaid",
        "orderRefund",
        "orderVoid",
      ],
      ["saleor:orders:write", "saleor:payments:write"],
    ],
    [["orderBulkCreate"], ["saleor:order-imports:write"]],
    [
      [
        "checkoutAddPromoCode",
        "checkoutBillingAddressUpdate",
        "checkoutCreate",
        "checkoutCreateFromOrder",
        "checkoutCustomerAttach",
        "checkoutCustomerDetach",
        "checkoutCustomerNoteUpdate",
        "checkoutEmailUpdate",
        "checkoutLineDelete",
        "checkoutLinesDelete",
        "checkoutLinesAdd",
        "checkoutLinesUpdate",
        "checkoutRemovePromoCode",
        "checkoutShippingAddressUpdate",
        "checkoutShippingMethodUpdate",
        "checkoutDeliveryMethodUpdate",
        "checkoutLanguageCodeUpdate",
        "orderCreateFromCheckout",
      ],
      ["saleor:checkouts:write"],
    ],
    [
      ["checkoutComplete", "checkoutPaymentCreate"],
      ["saleor:checkouts:write", "saleor:payments:write"],
    ],
    [
      [
        "paymentCapture",
        "paymentRefund",
        "paymentVoid",
        "paymentInitialize",
        "paymentCheckBalance",
        "transactionCreate",
        "transactionUpdate",
        "transactionRequestAction",
        "transactionRequestRefundForGrantedRefund",
        "transactionEventReport",
        "paymentGatewayInitialize",
        "transactionInitialize",
        "transactionProcess",
        "storedPaymentMethodRequestDelete",
        "paymentGatewayInitializeTokenization",
        "paymentMethodInitializeTokenization",
        "paymentMethodProcessTokenization",
      ],
      ["saleor:payments:write"],
    ],
    [
      [
        "addressCreate",
        "addressUpdate",
        "addressDelete",
        "addressSetDefault",
        "customerCreate",
        "customerUpdate",
        "customerDelete",
        "customerBulkDelete",
        "customerBulkUpdate",
        "userBulkSetActive",
      ],
      ["saleor:customers:write"],
    ],
    [
      [
        "tokenCreate",
        "tokenRefresh",
        "tokenVerify",
        "tokensDeactivateAll",
        "externalAuthenticationUrl",
        "externalObtainAccessTokens",
        "externalRefresh",
        "externalLogout",
        "externalVerify",
        "requestPasswordReset",
        "sendConfirmationEmail",
        "confirmAccount",
        "setPassword",
        "passwordChange",
        "requestEmailChange",
        "confirmEmailChange",
        "accountAddressCreate",
        "accountAddressUpdate",
        "accountAddressDelete",
        "accountSetDefaultAddress",
        "accountRegister",
        "accountUpdate",
        "accountRequestDeletion",
        "accountDelete",
        "userAvatarUpdate",
        "userAvatarDelete",
      ],
      ["saleor:identity:write"],
    ],
    [
      [
        "staffCreate",
        "staffUpdate",
        "staffDelete",
        "staffBulkDelete",
        "permissionGroupCreate",
        "permissionGroupUpdate",
        "permissionGroupDelete",
      ],
      ["saleor:staff:write"],
    ],
    [
      [
        "promotionCreate",
        "promotionUpdate",
        "promotionDelete",
        "promotionRuleCreate",
        "promotionRuleUpdate",
        "promotionRuleDelete",
        "promotionBulkDelete",
        "saleCreate",
        "saleDelete",
        "saleBulkDelete",
        "saleUpdate",
        "saleCataloguesAdd",
        "saleCataloguesRemove",
        "saleChannelListingUpdate",
        "voucherCreate",
        "voucherDelete",
        "voucherBulkDelete",
        "voucherUpdate",
        "voucherCataloguesAdd",
        "voucherCataloguesRemove",
        "voucherChannelListingUpdate",
        "voucherCodeBulkDelete",
      ],
      ["saleor:discounts:write"],
    ],
    [
      [
        "giftCardSettingsUpdate",
        "giftCardActivate",
        "giftCardCreate",
        "giftCardDelete",
        "giftCardDeactivate",
        "giftCardUpdate",
        "giftCardResend",
        "giftCardAddNote",
        "giftCardBulkCreate",
        "giftCardBulkDelete",
        "giftCardBulkActivate",
        "giftCardBulkDeactivate",
      ],
      ["saleor:gift-cards:write"],
    ],
    [
      [
        "pageCreate",
        "pageDelete",
        "pageBulkDelete",
        "pageBulkPublish",
        "pageUpdate",
        "pageTypeCreate",
        "pageTypeUpdate",
        "pageTypeDelete",
        "pageTypeBulkDelete",
        "pageAttributeAssign",
        "pageAttributeUnassign",
        "pageTypeReorderAttributes",
        "pageReorderAttributeValues",
      ],
      ["saleor:content:write"],
    ],
    [
      [
        "menuCreate",
        "menuDelete",
        "menuBulkDelete",
        "menuUpdate",
        "menuItemCreate",
        "menuItemDelete",
        "menuItemBulkDelete",
        "menuItemUpdate",
        "menuItemMove",
      ],
      ["saleor:navigation:write"],
    ],
    [["assignNavigation"], ["saleor:navigation:write", "saleor:settings:write"]],
    [
      [
        "shippingMethodChannelListingUpdate",
        "shippingPriceCreate",
        "shippingPriceDelete",
        "shippingPriceBulkDelete",
        "shippingPriceUpdate",
        "shippingPriceExcludeProducts",
        "shippingPriceRemoveProductFromExclude",
        "shippingZoneCreate",
        "shippingZoneDelete",
        "shippingZoneBulkDelete",
        "shippingZoneUpdate",
      ],
      ["saleor:shipping:write"],
    ],
    [
      [
        "taxClassCreate",
        "taxClassDelete",
        "taxClassUpdate",
        "taxConfigurationUpdate",
        "taxCountryConfigurationUpdate",
        "taxCountryConfigurationDelete",
        "taxExemptionManage",
      ],
      ["saleor:taxes:write"],
    ],
    [
      [
        "shopSettingsTranslate",
        "shippingPriceTranslate",
        "categoryTranslate",
        "collectionTranslate",
        "productBulkTranslate",
        "productTranslate",
        "productVariantTranslate",
        "productVariantBulkTranslate",
        "pageTranslate",
        "menuItemTranslate",
        "promotionTranslate",
        "promotionRuleTranslate",
        "saleTranslate",
        "voucherTranslate",
        "attributeTranslate",
        "attributeBulkTranslate",
        "attributeValueBulkTranslate",
        "attributeValueTranslate",
      ],
      ["saleor:translations:write"],
    ],
    [
      [
        "channelCreate",
        "channelDelete",
        "channelActivate",
        "channelDeactivate",
        "channelReorderWarehouses",
      ],
      ["saleor:channels:write"],
    ],
    [["channelUpdate"], ["saleor:channels:write"]],
    [
      [
        "appCreate",
        "appUpdate",
        "appDelete",
        "appTokenCreate",
        "appTokenDelete",
        "appTokenVerify",
        "appInstall",
        "appRetryInstall",
        "appDeleteFailedInstallation",
        "appFetchManifest",
        "appActivate",
        "appDeactivate",
        "appReenableSyncWebhooks",
      ],
      ["saleor:apps:write"],
    ],
    [
      [
        "webhookCreate",
        "webhookDelete",
        "webhookUpdate",
        "eventDeliveryRetry",
        "webhookDryRun",
        "webhookTrigger",
      ],
      ["saleor:webhooks:write"],
    ],
    [
      [
        "staffNotificationRecipientCreate",
        "staffNotificationRecipientUpdate",
        "staffNotificationRecipientDelete",
        "shopDomainUpdate",
        "shopSettingsUpdate",
        "shopFetchTaxRates",
        "shopAddressUpdate",
        "externalNotificationTrigger",
      ],
      ["saleor:settings:write"],
    ],
    [["pluginUpdate"], ["saleor:plugins:write"]],
    [["exportProducts"], ["saleor:catalog:read", "saleor:exports:write"]],
    [["exportGiftCards"], ["saleor:gift-cards:read", "saleor:exports:write"]],
    [["exportVoucherCodes"], ["saleor:discounts:read", "saleor:exports:write"]],
    [["fileUpload"], ["saleor:files:write"]],
    [
      ["deleteMetadata", "deletePrivateMetadata", "updateMetadata", "updatePrivateMetadata"],
      ["saleor:system:write"],
    ],
  ]),
};

export function requiredScopesForRootField(
  operation: RootOperationKind,
  field: string,
): readonly McpScope[] | undefined {
  return ROOT_FIELD_SCOPES[operation][field];
}
