# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import ChannelErrorCode


class ChannelCreate(BaseModel):
    channelCreate: Optional["ChannelCreateChannelCreate"]


class ChannelCreateChannelCreate(BaseModel):
    channel: Optional["ChannelCreateChannelCreateChannel"]
    errors: List["ChannelCreateChannelCreateErrors"]


class ChannelCreateChannelCreateChannel(BaseModel):
    id: str
    slug: str
    name: str
    isActive: bool
    currencyCode: str
    defaultCountry: "ChannelCreateChannelCreateChannelDefaultCountry"


class ChannelCreateChannelCreateChannelDefaultCountry(BaseModel):
    code: str


class ChannelCreateChannelCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ChannelErrorCode


ChannelCreate.model_rebuild()
ChannelCreateChannelCreate.model_rebuild()
ChannelCreateChannelCreateChannel.model_rebuild()
