# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Any, Dict, List, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .channel_create import ChannelCreate
from .count_orders import CountOrders
from .input_types import (
    ChannelCreateInput,
    CustomerFilterInput,
    OrderFilterInput,
    OrderSortingInput,
    ProductChannelListingUpdateInput,
    ProductCreateInput,
    ProductOrder,
    ProductTypeInput,
    ProductVariantChannelListingAddInput,
    ProductVariantCreateInput,
    ProductWhereInput,
    ShippingZoneUpdateInput,
    StockFilterInput,
    UserSortingInput,
)
from .list_channels import ListChannels
from .list_customers import ListCustomers
from .list_orders import ListOrders
from .list_products import ListProducts
from .list_shipping_zones import ListShippingZones
from .list_stocks import ListStocks
from .product_channel_listing_update import ProductChannelListingUpdate
from .shipping_zone_update import ShippingZoneUpdate
from .product_create import ProductCreate
from .product_type_create import ProductTypeCreate
from .product_variant_channel_listing_update import ProductVariantChannelListingUpdate
from .product_variant_create import ProductVariantCreate
from .warehouse_details import WarehouseDetails


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def count_orders(
        self,
        filter: Union[Optional[OrderFilterInput], UnsetType] = UNSET,
        **kwargs: Any
    ) -> CountOrders:
        query = gql(
            """
            query CountOrders($filter: OrderFilterInput) {
              orders(filter: $filter) {
                totalCount
              }
            }
            """
        )
        variables: Dict[str, object] = {"filter": filter}
        response = await self.execute(
            query=query, operation_name="CountOrders", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CountOrders.model_validate(data)

    async def list_channels(self, **kwargs: Any) -> ListChannels:
        query = gql(
            """
            query ListChannels {
              channels {
                id
                slug
                name
                isActive
                currencyCode
                defaultCountry {
                  code
                }
                warehouses {
                  id
                  name
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="ListChannels", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListChannels.model_validate(data)

    async def list_customers(
        self,
        first: Union[Optional[int], UnsetType] = UNSET,
        after: Union[Optional[str], UnsetType] = UNSET,
        sortBy: Union[Optional[UserSortingInput], UnsetType] = UNSET,
        filter: Union[Optional[CustomerFilterInput], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ListCustomers:
        query = gql(
            """
            query ListCustomers($first: Int, $after: String, $sortBy: UserSortingInput, $filter: CustomerFilterInput) {
              customers(first: $first, after: $after, sortBy: $sortBy, filter: $filter) {
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                  startCursor
                  endCursor
                }
                totalCount
                edges {
                  node {
                    id
                    isActive
                    languageCode
                    lastLogin
                    dateJoined
                    defaultShippingAddress {
                      country {
                        code
                      }
                    }
                    defaultBillingAddress {
                      country {
                        code
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "first": first,
            "after": after,
            "sortBy": sortBy,
            "filter": filter,
        }
        response = await self.execute(
            query=query, operation_name="ListCustomers", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListCustomers.model_validate(data)

    async def list_orders(
        self,
        first: Union[Optional[int], UnsetType] = UNSET,
        after: Union[Optional[str], UnsetType] = UNSET,
        sortBy: Union[Optional[OrderSortingInput], UnsetType] = UNSET,
        filter: Union[Optional[OrderFilterInput], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ListOrders:
        query = gql(
            """
            query ListOrders($first: Int, $after: String, $sortBy: OrderSortingInput, $filter: OrderFilterInput) {
              orders(first: $first, after: $after, sortBy: $sortBy, filter: $filter) {
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                  startCursor
                  endCursor
                }
                totalCount
                edges {
                  node {
                    id
                    number
                    status
                    created
                    updatedAt
                    paymentStatus
                    total {
                      gross {
                        amount
                        currency
                      }
                    }
                    lines {
                      quantity
                      productSku
                      variant {
                        name
                        product {
                          id
                          name
                        }
                      }
                      unitPrice {
                        gross {
                          currency
                          amount
                        }
                      }
                    }
                    shippingAddress {
                      country {
                        code
                      }
                    }
                    billingAddress {
                      country {
                        code
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "first": first,
            "after": after,
            "sortBy": sortBy,
            "filter": filter,
        }
        response = await self.execute(
            query=query, operation_name="ListOrders", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListOrders.model_validate(data)

    async def list_products(
        self,
        first: Union[Optional[int], UnsetType] = UNSET,
        after: Union[Optional[str], UnsetType] = UNSET,
        channel: Union[Optional[str], UnsetType] = UNSET,
        where: Union[Optional[ProductWhereInput], UnsetType] = UNSET,
        sortBy: Union[Optional[ProductOrder], UnsetType] = UNSET,
        search: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ListProducts:
        query = gql(
            """
            query ListProducts($first: Int, $after: String, $channel: String, $where: ProductWhereInput, $sortBy: ProductOrder, $search: String) {
              products(
                first: $first
                after: $after
                channel: $channel
                where: $where
                sortBy: $sortBy
                search: $search
              ) {
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                  startCursor
                  endCursor
                }
                totalCount
                edges {
                  node {
                    id
                    name
                    slug
                    externalReference
                    productType {
                      id
                      name
                    }
                    category {
                      id
                      name
                    }
                    defaultVariant {
                      id
                    }
                    productVariants(first: 20) {
                      edges {
                        node {
                          id
                          name
                          sku
                        }
                      }
                    }
                    created
                    updatedAt
                    thumbnail {
                      url
                    }
                    pricing {
                      priceRange {
                        start {
                          gross {
                            currency
                            amount
                          }
                        }
                        stop {
                          gross {
                            currency
                            amount
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "first": first,
            "after": after,
            "channel": channel,
            "where": where,
            "sortBy": sortBy,
            "search": search,
        }
        response = await self.execute(
            query=query, operation_name="ListProducts", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListProducts.model_validate(data)

    async def list_stocks(
        self,
        first: Union[Optional[int], UnsetType] = UNSET,
        after: Union[Optional[str], UnsetType] = UNSET,
        filter: Union[Optional[StockFilterInput], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ListStocks:
        query = gql(
            """
            query ListStocks($first: Int, $after: String, $filter: StockFilterInput) {
              stocks(first: $first, after: $after, filter: $filter) {
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                  startCursor
                  endCursor
                }
                totalCount
                edges {
                  node {
                    id
                    quantity
                    quantityAllocated
                    warehouse {
                      id
                    }
                    productVariant {
                      id
                      name
                      product {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "first": first,
            "after": after,
            "filter": filter,
        }
        response = await self.execute(
            query=query, operation_name="ListStocks", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListStocks.model_validate(data)

    async def warehouse_details(
        self, id: Union[Optional[str], UnsetType] = UNSET, **kwargs: Any
    ) -> WarehouseDetails:
        query = gql(
            """
            query WarehouseDetails($id: ID) {
              warehouse(id: $id) {
                id
                name
                slug
                address {
                  city
                  postalCode
                  country {
                    code
                  }
                }
                clickAndCollectOption
                shippingZones(first: 100) {
                  edges {
                    node {
                      id
                      name
                      description
                      channels {
                        id
                        slug
                        name
                      }
                      countries {
                        code
                      }
                    }
                  }
                }
                metadata {
                  key
                  value
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query,
            operation_name="WarehouseDetails",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return WarehouseDetails.model_validate(data)

    # Mutations
    async def channel_create(
        self, input: ChannelCreateInput, **kwargs: Any
    ) -> ChannelCreate:
        query = gql(
            """
            mutation ChannelCreate($input: ChannelCreateInput!) {
              channelCreate(input: $input) {
                channel {
                  id
                  slug
                  name
                  isActive
                  currencyCode
                  defaultCountry {
                    code
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="ChannelCreate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ChannelCreate.model_validate(data)

    async def product_type_create(
        self, input: ProductTypeInput, **kwargs: Any
    ) -> ProductTypeCreate:
        query = gql(
            """
            mutation ProductTypeCreate($input: ProductTypeInput!) {
              productTypeCreate(input: $input) {
                productType {
                  id
                  name
                  slug
                  isDigital
                  isShippingRequired
                  hasVariants
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="ProductTypeCreate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ProductTypeCreate.model_validate(data)

    async def product_create(
        self, input: ProductCreateInput, **kwargs: Any
    ) -> ProductCreate:
        query = gql(
            """
            mutation ProductCreate($input: ProductCreateInput!) {
              productCreate(input: $input) {
                product {
                  id
                  name
                  slug
                  productType {
                    id
                    name
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="ProductCreate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ProductCreate.model_validate(data)

    async def product_variant_create(
        self, input: ProductVariantCreateInput, **kwargs: Any
    ) -> ProductVariantCreate:
        query = gql(
            """
            mutation ProductVariantCreate($input: ProductVariantCreateInput!) {
              productVariantCreate(input: $input) {
                productVariant {
                  id
                  name
                  sku
                  product {
                    id
                    name
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="ProductVariantCreate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ProductVariantCreate.model_validate(data)

    async def product_channel_listing_update(
        self, id: str, input: ProductChannelListingUpdateInput, **kwargs: Any
    ) -> ProductChannelListingUpdate:
        query = gql(
            """
            mutation ProductChannelListingUpdate($id: ID!, $input: ProductChannelListingUpdateInput!) {
              productChannelListingUpdate(id: $id, input: $input) {
                product {
                  id
                  name
                  channelListings {
                    id
                    channel {
                      id
                      slug
                      name
                    }
                    isPublished
                    isAvailableForPurchase
                    visibleInListings
                  }
                }
                errors {
                  field
                  message
                  code
                  channels
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query,
            operation_name="ProductChannelListingUpdate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ProductChannelListingUpdate.model_validate(data)

    async def product_variant_channel_listing_update(
        self, id: str, input: List[ProductVariantChannelListingAddInput], **kwargs: Any
    ) -> ProductVariantChannelListingUpdate:
        query = gql(
            """
            mutation ProductVariantChannelListingUpdate($id: ID!, $input: [ProductVariantChannelListingAddInput!]!) {
              productVariantChannelListingUpdate(id: $id, input: $input) {
                variant {
                  id
                  name
                  channelListings {
                    id
                    channel {
                      id
                      slug
                    }
                    price {
                      amount
                      currency
                    }
                  }
                }
                errors {
                  field
                  message
                  code
                  channels
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query,
            operation_name="ProductVariantChannelListingUpdate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ProductVariantChannelListingUpdate.model_validate(data)

    async def list_shipping_zones(
        self,
        first: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ListShippingZones:
        query = gql(
            """
            query ListShippingZones($first: Int = 20) {
                shippingZones(first: $first) {
                    edges {
                        node {
                            id
                            name
                            warehouses {
                                id
                                name
                            }
                            channels {
                                id
                                name
                                slug
                            }
                        }
                    }
                }
            }
            """
        )
        variables: Dict[str, object] = {"first": first}
        response = await self.execute(
            query=query,
            operation_name="ListShippingZones",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ListShippingZones.model_validate(data)

    async def shipping_zone_update(
        self, id: str, input: ShippingZoneUpdateInput, **kwargs: Any
    ) -> ShippingZoneUpdate:
        query = gql(
            """
            mutation ShippingZoneUpdate($id: ID!, $input: ShippingZoneUpdateInput!) {
                shippingZoneUpdate(id: $id, input: $input) {
                    shippingZone {
                        id
                        name
                        warehouses {
                            id
                            name
                        }
                        channels {
                            id
                            name
                            slug
                        }
                    }
                    errors {
                        field
                        message
                        code
                    }
                }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query,
            operation_name="ShippingZoneUpdate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ShippingZoneUpdate.model_validate(data)
