# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Optional

from .base_model import BaseModel


class CountOrders(BaseModel):
    orders: Optional["CountOrdersOrders"]


class CountOrdersOrders(BaseModel):
    totalCount: Optional[int]


CountOrders.model_rebuild()
