# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from .base_model import BaseModel


class Address(BaseModel):
    firstName: str
    lastName: str
    streetAddress1: str
    streetAddress2: str
    country: "AddressCountry"
    postalCode: str


class AddressCountry(BaseModel):
    code: str


Address.model_rebuild()
