# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class ListProducts(BaseModel):
    products: Optional["ListProductsProducts"]


class ListProductsProducts(BaseModel):
    pageInfo: "ListProductsProductsPageInfo"
    totalCount: Optional[int]
    edges: List["ListProductsProductsEdges"]


class ListProductsProductsPageInfo(BaseModel):
    hasNextPage: bool
    hasPreviousPage: bool
    startCursor: Optional[str]
    endCursor: Optional[str]


class ListProductsProductsEdges(BaseModel):
    node: "ListProductsProductsEdgesNode"


class ListProductsProductsEdgesNode(BaseModel):
    id: str
    name: str
    slug: str
    externalReference: Optional[str]
    productType: "ListProductsProductsEdgesNodeProductType"
    category: Optional["ListProductsProductsEdgesNodeCategory"]
    created: Any
    updatedAt: Any
    pricing: Optional["ListProductsProductsEdgesNodePricing"]


class ListProductsProductsEdgesNodeProductType(BaseModel):
    id: str
    name: str


class ListProductsProductsEdgesNodeCategory(BaseModel):
    id: str
    name: str


class ListProductsProductsEdgesNodePricing(BaseModel):
    priceRange: Optional["ListProductsProductsEdgesNodePricingPriceRange"]


class ListProductsProductsEdgesNodePricingPriceRange(BaseModel):
    start: Optional["ListProductsProductsEdgesNodePricingPriceRangeStart"]
    stop: Optional["ListProductsProductsEdgesNodePricingPriceRangeStop"]


class ListProductsProductsEdgesNodePricingPriceRangeStart(BaseModel):
    gross: "ListProductsProductsEdgesNodePricingPriceRangeStartGross"


class ListProductsProductsEdgesNodePricingPriceRangeStartGross(BaseModel):
    currency: str
    amount: float


class ListProductsProductsEdgesNodePricingPriceRangeStop(BaseModel):
    gross: "ListProductsProductsEdgesNodePricingPriceRangeStopGross"


class ListProductsProductsEdgesNodePricingPriceRangeStopGross(BaseModel):
    currency: str
    amount: float


ListProducts.model_rebuild()
ListProductsProducts.model_rebuild()
ListProductsProductsEdges.model_rebuild()
ListProductsProductsEdgesNode.model_rebuild()
ListProductsProductsEdgesNodePricing.model_rebuild()
ListProductsProductsEdgesNodePricingPriceRange.model_rebuild()
ListProductsProductsEdgesNodePricingPriceRangeStart.model_rebuild()
ListProductsProductsEdgesNodePricingPriceRangeStop.model_rebuild()
