# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel


class ListChannels(BaseModel):
    channels: Optional[List["ListChannelsChannels"]]


class ListChannelsChannels(BaseModel):
    id: str
    slug: str
    name: str
    isActive: bool
    currencyCode: str
    defaultCountry: "ListChannelsChannelsDefaultCountry"
    warehouses: List["ListChannelsChannelsWarehouses"]


class ListChannelsChannelsDefaultCountry(BaseModel):
    code: str


class ListChannelsChannelsWarehouses(BaseModel):
    id: str
    name: str


ListChannels.model_rebuild()
ListChannelsChannels.model_rebuild()
