# Generated by ariadne-codegen (manual addition)

from typing import List, Optional

from .base_model import BaseModel


class ListShippingZonesShippingZonesEdgesNodeWarehousesItem(BaseModel):
    id: str
    name: str


class ListShippingZonesShippingZonesEdgesNodeChannelsItem(BaseModel):
    id: str
    name: str
    slug: str


class ListShippingZonesShippingZonesEdgesNode(BaseModel):
    id: str
    name: str
    warehouses: List[ListShippingZonesShippingZonesEdgesNodeWarehousesItem]
    channels: List[ListShippingZonesShippingZonesEdgesNodeChannelsItem]


class ListShippingZonesShippingZonesEdges(BaseModel):
    node: ListShippingZonesShippingZonesEdgesNode


class ListShippingZonesShippingZones(BaseModel):
    edges: List[ListShippingZonesShippingZonesEdges]


class ListShippingZones(BaseModel):
    shippingZones: Optional[ListShippingZonesShippingZones] = None

