# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Any, List, Optional

from .base_model import BaseModel
from .enums import OrderStatus, PaymentChargeStatusEnum
from .fragments import Address


class ListOrders(BaseModel):
    orders: Optional["ListOrdersOrders"]


class ListOrdersOrders(BaseModel):
    pageInfo: "ListOrdersOrdersPageInfo"
    totalCount: Optional[int]
    edges: List["ListOrdersOrdersEdges"]


class ListOrdersOrdersPageInfo(BaseModel):
    hasNextPage: bool
    hasPreviousPage: bool
    startCursor: Optional[str]
    endCursor: Optional[str]


class ListOrdersOrdersEdges(BaseModel):
    node: "ListOrdersOrdersEdgesNode"


class ListOrdersOrdersEdgesNode(BaseModel):
    id: str
    number: str
    status: OrderStatus
    created: Any
    updatedAt: Any
    paymentStatus: PaymentChargeStatusEnum
    userEmail: Optional[str]
    total: "ListOrdersOrdersEdgesNodeTotal"
    lines: List["ListOrdersOrdersEdgesNodeLines"]
    shippingAddress: Optional["ListOrdersOrdersEdgesNodeShippingAddress"]
    billingAddress: Optional["ListOrdersOrdersEdgesNodeBillingAddress"]


class ListOrdersOrdersEdgesNodeTotal(BaseModel):
    gross: "ListOrdersOrdersEdgesNodeTotalGross"


class ListOrdersOrdersEdgesNodeTotalGross(BaseModel):
    amount: float
    currency: str


class ListOrdersOrdersEdgesNodeLines(BaseModel):
    quantity: int
    productSku: Optional[str]
    variant: Optional["ListOrdersOrdersEdgesNodeLinesVariant"]
    unitPrice: "ListOrdersOrdersEdgesNodeLinesUnitPrice"


class ListOrdersOrdersEdgesNodeLinesVariant(BaseModel):
    name: str
    product: "ListOrdersOrdersEdgesNodeLinesVariantProduct"


class ListOrdersOrdersEdgesNodeLinesVariantProduct(BaseModel):
    id: str
    name: str


class ListOrdersOrdersEdgesNodeLinesUnitPrice(BaseModel):
    gross: "ListOrdersOrdersEdgesNodeLinesUnitPriceGross"


class ListOrdersOrdersEdgesNodeLinesUnitPriceGross(BaseModel):
    currency: str
    amount: float


class ListOrdersOrdersEdgesNodeShippingAddress(Address):
    pass


class ListOrdersOrdersEdgesNodeBillingAddress(Address):
    pass


ListOrders.model_rebuild()
ListOrdersOrders.model_rebuild()
ListOrdersOrdersEdges.model_rebuild()
ListOrdersOrdersEdgesNode.model_rebuild()
ListOrdersOrdersEdgesNodeTotal.model_rebuild()
ListOrdersOrdersEdgesNodeLines.model_rebuild()
ListOrdersOrdersEdgesNodeLinesVariant.model_rebuild()
ListOrdersOrdersEdgesNodeLinesUnitPrice.model_rebuild()
