# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel


class ListStocks(BaseModel):
    stocks: Optional["ListStocksStocks"]


class ListStocksStocks(BaseModel):
    pageInfo: "ListStocksStocksPageInfo"
    totalCount: Optional[int]
    edges: List["ListStocksStocksEdges"]


class ListStocksStocksPageInfo(BaseModel):
    hasNextPage: bool
    hasPreviousPage: bool
    startCursor: Optional[str]
    endCursor: Optional[str]


class ListStocksStocksEdges(BaseModel):
    node: "ListStocksStocksEdgesNode"


class ListStocksStocksEdgesNode(BaseModel):
    id: str
    quantity: int
    quantityAllocated: int
    warehouse: "ListStocksStocksEdgesNodeWarehouse"
    productVariant: "ListStocksStocksEdgesNodeProductVariant"


class ListStocksStocksEdgesNodeWarehouse(BaseModel):
    id: str


class ListStocksStocksEdgesNodeProductVariant(BaseModel):
    id: str
    name: str
    product: "ListStocksStocksEdgesNodeProductVariantProduct"


class ListStocksStocksEdgesNodeProductVariantProduct(BaseModel):
    id: str
    name: str


ListStocks.model_rebuild()
ListStocksStocks.model_rebuild()
ListStocksStocksEdges.model_rebuild()
ListStocksStocksEdgesNode.model_rebuild()
ListStocksStocksEdgesNodeProductVariant.model_rebuild()
