# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Any, List, Optional

from .base_model import BaseModel
from .enums import LanguageCodeEnum


class ListCustomers(BaseModel):
    customers: Optional["ListCustomersCustomers"]


class ListCustomersCustomers(BaseModel):
    pageInfo: "ListCustomersCustomersPageInfo"
    totalCount: Optional[int]
    edges: List["ListCustomersCustomersEdges"]


class ListCustomersCustomersPageInfo(BaseModel):
    hasNextPage: bool
    hasPreviousPage: bool
    startCursor: Optional[str]
    endCursor: Optional[str]


class ListCustomersCustomersEdges(BaseModel):
    node: "ListCustomersCustomersEdgesNode"


class ListCustomersCustomersEdgesNode(BaseModel):
    id: str
    email: str
    firstName: str
    lastName: str
    isActive: bool
    isConfirmed: bool
    checkouts: Optional["ListCustomersCustomersEdgesNodeCheckouts"]
    orders: Optional["ListCustomersCustomersEdgesNodeOrders"]
    languageCode: LanguageCodeEnum
    lastLogin: Optional[Any]
    dateJoined: Any
    defaultShippingAddress: Optional[
        "ListCustomersCustomersEdgesNodeDefaultShippingAddress"
    ]
    defaultBillingAddress: Optional[
        "ListCustomersCustomersEdgesNodeDefaultBillingAddress"
    ]


class ListCustomersCustomersEdgesNodeCheckouts(BaseModel):
    totalCount: Optional[int]


class ListCustomersCustomersEdgesNodeOrders(BaseModel):
    totalCount: Optional[int]


class ListCustomersCustomersEdgesNodeDefaultShippingAddress(BaseModel):
    firstName: str
    lastName: str
    streetAddress1: str
    streetAddress2: str
    country: "ListCustomersCustomersEdgesNodeDefaultShippingAddressCountry"
    postalCode: str


class ListCustomersCustomersEdgesNodeDefaultShippingAddressCountry(BaseModel):
    code: str


class ListCustomersCustomersEdgesNodeDefaultBillingAddress(BaseModel):
    firstName: str
    lastName: str
    streetAddress1: str
    streetAddress2: str
    country: "ListCustomersCustomersEdgesNodeDefaultBillingAddressCountry"
    postalCode: str


class ListCustomersCustomersEdgesNodeDefaultBillingAddressCountry(BaseModel):
    code: str


ListCustomers.model_rebuild()
ListCustomersCustomers.model_rebuild()
ListCustomersCustomersEdges.model_rebuild()
ListCustomersCustomersEdgesNode.model_rebuild()
ListCustomersCustomersEdgesNodeDefaultShippingAddress.model_rebuild()
ListCustomersCustomersEdgesNodeDefaultBillingAddress.model_rebuild()
