# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import ProductErrorCode


class ProductVariantCreate(BaseModel):
    productVariantCreate: Optional["ProductVariantCreateProductVariantCreate"]


class ProductVariantCreateProductVariantCreate(BaseModel):
    productVariant: Optional["ProductVariantCreateProductVariantCreateProductVariant"]
    errors: List["ProductVariantCreateProductVariantCreateErrors"]


class ProductVariantCreateProductVariantCreateProductVariant(BaseModel):
    id: str
    name: str
    sku: Optional[str]
    product: "ProductVariantCreateProductVariantCreateProductVariantProduct"


class ProductVariantCreateProductVariantCreateProductVariantProduct(BaseModel):
    id: str
    name: str


class ProductVariantCreateProductVariantCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode


ProductVariantCreate.model_rebuild()
ProductVariantCreateProductVariantCreate.model_rebuild()
ProductVariantCreateProductVariantCreateProductVariant.model_rebuild()
