# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import ProductErrorCode


class ProductCreate(BaseModel):
    productCreate: Optional["ProductCreateProductCreate"]


class ProductCreateProductCreate(BaseModel):
    product: Optional["ProductCreateProductCreateProduct"]
    errors: List["ProductCreateProductCreateErrors"]


class ProductCreateProductCreateProduct(BaseModel):
    id: str
    name: str
    slug: str
    productType: "ProductCreateProductCreateProductProductType"


class ProductCreateProductCreateProductProductType(BaseModel):
    id: str
    name: str


class ProductCreateProductCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode


ProductCreate.model_rebuild()
ProductCreateProductCreate.model_rebuild()
ProductCreateProductCreateProduct.model_rebuild()
