# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import ProductErrorCode


class ProductVariantChannelListingUpdate(BaseModel):
    productVariantChannelListingUpdate: Optional[
        "ProductVariantChannelListingUpdateProductVariantChannelListingUpdate"
    ]


class ProductVariantChannelListingUpdateProductVariantChannelListingUpdate(BaseModel):
    variant: Optional[
        "ProductVariantChannelListingUpdateProductVariantChannelListingUpdateVariant"
    ]
    errors: List[
        "ProductVariantChannelListingUpdateProductVariantChannelListingUpdateErrors"
    ]


class ProductVariantChannelListingUpdateProductVariantChannelListingUpdateVariant(
    BaseModel
):
    id: str
    name: str
    channelListings: Optional[
        List[
            "ProductVariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListings"
        ]
    ]


class ProductVariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListings(
    BaseModel
):
    id: str
    channel: "ProductVariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListingsChannel"
    price: Optional[
        "ProductVariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListingsPrice"
    ]


class ProductVariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListingsChannel(
    BaseModel
):
    id: str
    slug: str


class ProductVariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListingsPrice(
    BaseModel
):
    amount: float
    currency: str


class ProductVariantChannelListingUpdateProductVariantChannelListingUpdateErrors(
    BaseModel
):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode
    channels: Optional[List[str]]


ProductVariantChannelListingUpdate.model_rebuild()
ProductVariantChannelListingUpdateProductVariantChannelListingUpdate.model_rebuild()
ProductVariantChannelListingUpdateProductVariantChannelListingUpdateVariant.model_rebuild()
ProductVariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListings.model_rebuild()
