# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import ProductErrorCode


class ProductChannelListingUpdate(BaseModel):
    productChannelListingUpdate: Optional[
        "ProductChannelListingUpdateProductChannelListingUpdate"
    ]


class ProductChannelListingUpdateProductChannelListingUpdate(BaseModel):
    product: Optional["ProductChannelListingUpdateProductChannelListingUpdateProduct"]
    errors: List["ProductChannelListingUpdateProductChannelListingUpdateErrors"]


class ProductChannelListingUpdateProductChannelListingUpdateProduct(BaseModel):
    id: str
    name: str
    channelListings: Optional[
        List[
            "ProductChannelListingUpdateProductChannelListingUpdateProductChannelListings"
        ]
    ]


class ProductChannelListingUpdateProductChannelListingUpdateProductChannelListings(
    BaseModel
):
    id: str
    channel: "ProductChannelListingUpdateProductChannelListingUpdateProductChannelListingsChannel"
    isPublished: bool
    isAvailableForPurchase: Optional[bool]
    visibleInListings: bool


class ProductChannelListingUpdateProductChannelListingUpdateProductChannelListingsChannel(
    BaseModel
):
    id: str
    slug: str
    name: str


class ProductChannelListingUpdateProductChannelListingUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode
    channels: Optional[List[str]]


ProductChannelListingUpdate.model_rebuild()
ProductChannelListingUpdateProductChannelListingUpdate.model_rebuild()
ProductChannelListingUpdateProductChannelListingUpdateProduct.model_rebuild()
ProductChannelListingUpdateProductChannelListingUpdateProductChannelListings.model_rebuild()
