# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import ProductErrorCode


class ProductTypeCreate(BaseModel):
    productTypeCreate: Optional["ProductTypeCreateProductTypeCreate"]


class ProductTypeCreateProductTypeCreate(BaseModel):
    productType: Optional["ProductTypeCreateProductTypeCreateProductType"]
    errors: List["ProductTypeCreateProductTypeCreateErrors"]


class ProductTypeCreateProductTypeCreateProductType(BaseModel):
    id: str
    name: str
    slug: str
    isDigital: bool
    isShippingRequired: bool
    hasVariants: bool


class ProductTypeCreateProductTypeCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode


ProductTypeCreate.model_rebuild()
ProductTypeCreateProductTypeCreate.model_rebuild()
