# Generated by ariadne-codegen (manual addition)

from typing import List, Optional

from .base_model import BaseModel


class ShippingZoneUpdateShippingZoneUpdateWarehousesItem(BaseModel):
    id: str
    name: str


class ShippingZoneUpdateShippingZoneUpdateChannelsItem(BaseModel):
    id: str
    name: str
    slug: str


class ShippingZoneUpdateShippingZoneUpdateShippingZone(BaseModel):
    id: str
    name: str
    warehouses: List[ShippingZoneUpdateShippingZoneUpdateWarehousesItem]
    channels: List[ShippingZoneUpdateShippingZoneUpdateChannelsItem]


class ShippingZoneUpdateShippingZoneUpdateErrors(BaseModel):
    field: Optional[str] = None
    message: Optional[str] = None
    code: Optional[str] = None


class ShippingZoneUpdateShippingZoneUpdate(BaseModel):
    shippingZone: Optional[ShippingZoneUpdateShippingZoneUpdateShippingZone] = None
    errors: List[ShippingZoneUpdateShippingZoneUpdateErrors]


class ShippingZoneUpdate(BaseModel):
    shippingZoneUpdate: Optional[ShippingZoneUpdateShippingZoneUpdate] = None

