# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import WarehouseClickAndCollectOptionEnum


class WarehouseDetails(BaseModel):
    warehouse: Optional["WarehouseDetailsWarehouse"]


class WarehouseDetailsWarehouse(BaseModel):
    id: str
    name: str
    slug: str
    address: "WarehouseDetailsWarehouseAddress"
    clickAndCollectOption: WarehouseClickAndCollectOptionEnum
    shippingZones: "WarehouseDetailsWarehouseShippingZones"
    metadata: List["WarehouseDetailsWarehouseMetadata"]


class WarehouseDetailsWarehouseAddress(BaseModel):
    firstName: str
    lastName: str
    streetAddress1: str
    streetAddress2: str
    city: str
    postalCode: str


class WarehouseDetailsWarehouseShippingZones(BaseModel):
    edges: List["WarehouseDetailsWarehouseShippingZonesEdges"]


class WarehouseDetailsWarehouseShippingZonesEdges(BaseModel):
    node: "WarehouseDetailsWarehouseShippingZonesEdgesNode"


class WarehouseDetailsWarehouseShippingZonesEdgesNode(BaseModel):
    id: str
    name: str
    description: Optional[str]
    channels: List["WarehouseDetailsWarehouseShippingZonesEdgesNodeChannels"]
    countries: List["WarehouseDetailsWarehouseShippingZonesEdgesNodeCountries"]


class WarehouseDetailsWarehouseShippingZonesEdgesNodeChannels(BaseModel):
    id: str
    slug: str
    name: str


class WarehouseDetailsWarehouseShippingZonesEdgesNodeCountries(BaseModel):
    code: str
    country: str


class WarehouseDetailsWarehouseMetadata(BaseModel):
    key: str
    value: str


WarehouseDetails.model_rebuild()
WarehouseDetailsWarehouse.model_rebuild()
WarehouseDetailsWarehouseShippingZones.model_rebuild()
WarehouseDetailsWarehouseShippingZonesEdges.model_rebuild()
WarehouseDetailsWarehouseShippingZonesEdgesNode.model_rebuild()
